# Generated by Django 3.1.4 on 2020-12-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=250, verbose_name='Регион')),
                ('request_words', models.CharField(max_length=250, verbose_name='Ключевые слова')),
                ('date', models.DateTimeField(verbose_name='Двта запроса')),
            ],
        ),
    ]
